image: node:18-alpine

stages:
  - build

build-job:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - DISABLE_ESLINT_PLUGIN=true CI=false npm run build
  artifacts:
    paths:
      - build/

