stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy


variables:
  APP_PATH: '$CI_PROJECT_DIR'
  OUTPUT_PATH: '$CI_PROJECT_DIR/build'


deploy-development:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: development
  variables:
    API_TOKEN: $DEPLOYMENT_TOKEN_DEV
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "Deploying Development application..."
    - echo "Development Application successfully deployed."
  only:
    - development

deploy-production:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  variables:
    API_TOKEN: $DEPLOYMENT_TOKEN
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "Deploying Production application..."
    - echo "Production Application successfully deployed."
  only:
  - master
