import { Link, Typography } from "@mui/material"

import {AppRoutes} from '../../../utils/consts/routes'

const TermsAndConditionsConst = {
  title:"Terms and Conditions",
  items:[
    {
      title:"PURPOSE",
      paragraphs:[
        'Uden.tech is intended only to serve as a preliminary medium of contact and exchange of information for its users / members / visitors who have a bona fide intention to contact and/or be contacted for the purposes related to genuine existing job vacancies and for other career enhancement services.'
      ]
    },
    {
      title:"USE TO BE IN CONFORMITY WITH THE PURPOSE",
      paragraphs:[
        'Uden.tech (and related products) or service or product that is subscribe to or used (whether the same is paid for by you or not) is meant for the Purpose  and only the exclusive use of the subscriber/registered user. Copying or downloading or recreating or sharing passwords or sublicensing or sharing in any manner which is not in accordance with these terms, is a misuse of the platform or service or product and DSPL reserves its rights to act in such manner as to protect its loss of revenue or reputation or claim damages including stopping your service or access and reporting to relevant authorities. In the event you are found to be copying or misusing or transmitting or crawling any data or photographs or graphics or any information available on Uden.tech for any purpose other than that being a bonafide Purpose, we reserve the right to take such action that we deem fit including stopping access and claiming damages',
        'The site is a public site with free access and Digverve assumes no liability for the quality and genuineness of responses. Digverve Solutions Pvt. Ltd. (DSPL) cannot monitor the responses that a person may receive in response to information he/she has displayed on the site. The individual/company would have to conduct its own background checks on the bonafide nature of all response(s).',
        'You give us permission to use the information about actions that you have taken on Uden.tech in connection with ads, offers and other content (whether sponsored or not) that we display across our services, without any compensation to you. We use data and information about you to make relevant suggestions and recommendation to you and others.',
        'The platform may contain links to third party websites, these links are provided solely as convenience to You and the presence of these links should not under any circumstances be considered as an endorsement of the contents of the same, if You chose to access these websites you do so at your own risk.',
        'Whilst using this platform an obligation is cast upon you to only provide true and correct information and in the case of creating a profile you undertake to at all times keep the information up to date. Digverve Solutions Pvt. Ltd. will not be liable on account of any inaccuracy of information on this web site. It is the responsibility of the visitor to further research the information on the site. Any breach of privacy or of the information provided by the consumer to Digverve Solutions Pvt. Ltd. to be placed on the website by technical or any other means is not the responsibility of Digverve Solutions Pvt. Ltd. Digverve Solutions Pvt. Ltd. does not guarantee confidentiality of information provided to it by any person acquiring/using all/any information displayed on the Uden.tech website or any of its other websites / domains owned and operated by Digverve Solutions Pvt. Ltd.',
        'Digverve Solutions Pvt. Ltd. does not share personally identifiable data of any individual with other companies / entities without obtaining permission except with those acting as our agents.. Digverve Solutions Pvt. Ltd. shall share all such information that it has in its possession in response to legal process, such as a court order or subpoena. The user shall not utilize the services offered by Uden.tech/DSPL in any manner so as to impair the interests and functioning of Uden.tech/DSPL. The user undertakes not to duplicate, download publish, modify and distribute material on Uden.tech unless specifically authorized by DSPL in this regard.',
        'The user undertakes to use Uden.tech for his/her own purposes. Using content from Uden.tech for derivative works with a commercial motive without prior written consent from DSPL is strictly prohibited.',
        'Users undertake that the services offered by Uden.tech/ DSPL shall not be utilized to upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail. DSPL reserves the right to filter and monitor and block the emails sent by you/user using the servers maintained by DSPL to relay emails. All attempts shall be made by DSPL and the user to abide by International Best Practices in containing and eliminating Spam.',
        'Users shall not spam the platform maintained by Uden.tech / DSPL or indiscriminately and repeatedly post jobs/forward mail indiscriminately etc. Any conduct of the user in violation of this clause shall entitle DSPL to forthwith terminate all services to the user without notice and to forfeit any amounts paid by him.',
        'The user shall not upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous, vulgar, obscene, or racially, ethnically, or otherwise objectionable.',
        'The user expressly states that the resume/insertion or information/ data being fed into the network of Digverve Solutions Pvt. Ltd. by the user is correct and complete in all respects and does not contain any false, distorted, manipulated, fraudulent or misleading facts or averments. Digverve Solutions Pvt. Ltd. expressly disclaims any liability arising out of the said resume insertion/information/ data so fed into the network of Digverve Solutions Pvt. Ltd. by the user. Further, the user agrees to indemnify Digverve Solutions Pvt. Ltd. for all losses incurred by Digverve Solutions Pvt. Ltd. due to any false, distorted, manipulated, defamatory, libelous, vulgar, obscene, fraudulent or misleading facts or otherwise objectionable averments made by the user on the network of Digverve.',
        'The User is solely responsible for maintaining confidentiality of the User password and user identification and all activities and transmission performed by the User through his user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and Digverve Solutions Pvt. Ltd. assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.',
        'The User/Subscriber/Visitor to Uden.tech and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made thereunder, while assessing or feeding any resume/ insertion or information/data into the computers, computer systems or computer network of Digverve. The said User/ subscriber/ visitor to Uden.tech and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, byelaws and notifications made thereunder, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.',
        'The User is solely responsible for obtaining, at his own cost, all licenses, permits, consents, approvals and intellectual property or other rights as may be required by the user for using the Service.'
      ]
    },
    {
      title:"THE USER REPRESENTS, WARRANTS AND COVENANTS THAT ITS USE OF UDEN.TECH SHALL NOT BE DONE IN A MANNER SO AS TO",
      paragraphs:[
        'Violate any applicable local, provincial, state, national or international law, statute, ordinance, rule or regulation.',
        'Interfere with or disrupt computer networks connected to Uden.tech.',
        'Impersonate any other person or entity, or make any misrepresentation as to your employment by or affiliation with any other person or entity.',
        'Forge headers or in any manner manipulate identifiers in order to disguise the origin of any user information.',
        'Interfere with or disrupt the use of Uden.tech by any other user, nor "stalk", threaten, or in any manner harass another user.',
        'Reproduce, copy, modify, sell, store, distribute or otherwise exploit for any commercial purposes Uden.tech, or any component thereof (including, but not limited to any materials or information accessible through Uden.tech).',
        'Use content from the Site for derivative works with a commercial motive without prior written consent of the DSPL.',
        'Use any device, software or routine to interfere or attempt to interfere with the proper working of Uden.tech; or',
        'Impose an unreasonable or disproportionately large load on Uden.tech infrastructure.',
        'Spam Uden.tech/DSPL by indiscriminately and repeatedly posting content or forwarding mail that may be considered spam etc.',
        'Access data not intended for you or log into server or account that you are not authorized to access.',
        'Constitute an act of reverse engineering, decompiling, disassembling, deciphering or otherwise attempting to derive the source code for the Site or any related technology or any part thereof',
        'Engage in "framing," "mirroring," or otherwise simulating the appearance or function of the Site',
        'Attempt to probe, scan or test the vulnerability of a system or network',
        'Use automated means to crawl and/or scrape content from Uden.tech and to manually scrape content from Uden.tech.',
        'The Site uses technological means to exclude Robots etc. from crawling it and scraping content. You undertake not to circumvent these methods.',
        'Access the Site except through the interfaces expressly provided by DSPL',
        'Attempt or breach security or authentication measures without proper authorization.',
        'Providing deeplinks into Uden.tech without prior permission of DSPL is prohibited. Extracting data from Uden.tech using any automated process such as spiders, crawlers etc. or through any manual process for a purpose which has not been authorised in writing.',
        'Upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail.',
        'Subscribers shall under no circumstance sublicense, assign, or transfer the License, and any attempt at such sublicense, assignment or transfer is void.',
        {
          title:"Constitute hosting, modifying, uploading, posting, transmitting, publishing, or distributing any material or information",
          paragraph:[
            'For which you do not have all necessary rights and licenses.',
            'Which infringes, violates, breaches or otherwise contravenes the rights of any third party, including any copyright, trademark, patent, rights of privacy or publicity or any other proprietary right.',
            'Which contains a computer virus, or other code, files or programs intending in any manner to disrupt or interfere with the functioning of Uden.tech, or that of other computer systems.',
            'That is grossly harmful, harassing, invasive of another\'s privacy, hateful, disparaging, relating to money laundering or unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libelous/blasphemous, vulgar, obscene, or racially, ethnically, or otherwise unlawful in any manner whatsoever',
            'Which constitutes or encourages conduct that would constitute a criminal offence, give rise to other liability, or otherwise violate applicable law',
            'That deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.',
            'That belongs to another person and to which the user does not have any right to',
            'That harm minors in any way',
            'That threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognisable offence or prevents investigation of any offence or is insulting any other nation.',
          ]
        },
        'The user shall not infringe on any intellectual property rights of any person / entity or retain information / download any information from any computer system or otherwise with an intention to do so.',
        'Digverve Solutions Pvt. Ltd. will make best efforts to do so but does not warrant that any of the web sites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. The subscription of a user shall be subject to Quotas as applicable and as advised. E-Mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorised personnel only.',
        'Digverve Solutions Pvt. Ltd. shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user\'s account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.',
        'Payments for the services offered by Uden.tech shall be on a 100% advance basis. Refund if any will be at the sole discretion of Digverve. DSPL offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts. DSPL gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only. DSPL undertakes no liability for free services. DSPL reserves its right to amend / alter or change all or any disclaimers or terms of agreements at any time without any prior notice. All terms / disclaimers whether specifically mentioned or not shall be deemed to be included if any reference is made to them.',
        'Unless otherwise specified and notwithstanding anything contained in any other agreement or arrangement, by whatever name called, the performance obligation of DSPL (service provider) is to provide access of its on-line portal to the customer for the duration of the subscription period & reference to any usage, by whatever name called or any other performance obligation, if any, is to provide the upper limit for consumption, which by itself, does not create any additional performance obligation upon DSPL',
        'Subscriber/user acknowledges and agrees that DSPL/Uden.tech, at its sole discretion and without prejudice to other rights and remedies that it may have under the applicable laws, shall be entitled to set off the amount paid or payable by a subscriber/user against any amount(s) payable by Subscriber/user to DSPL under any other agreement or commercial relationship towards other products/services.',
        'Digverve Solutions Pvt. Ltd. further reserves its right to post the data on the website Uden.tech or on such other affiliated sites and publications as Digverve Solutions Pvt. Ltd. may deem fit and proper at no extra cost to the subscriber / user.',
        'The subscription / agreement between DSPL and the subscriber / user is not a "non-poach agreement" nor can the same be termed or used as an alternative to "non-poach agreement" in as much as DSPL / Uden.tech is a public site and all information posted by DSPL goes to the public domain except information / data which is specifically assigned a non-public / private character.',
        'Any agreement for a subscription / usage entered into by DSPL does not confer exclusivity of service on any subscriber / user.',
        'Digverve (India) Ltd will not be party to any legal proceedings between a user (e.g. a subscriber) and a party contracted through the site. In case Digverve Solutions Pvt. Ltd. is implicated in any legal proceedings, costs will be recovered from the party that names Digverve Solutions Pvt. Ltd. Digverve however will abide with any court order served on it through due process. DSPL controls and operates this Platform from its headquarters in Noida and makes no representation that the materials on Uden.tech are appropriate or available for use in other locations. If you use this Website from other locations, you are responsible for compliance with applicable local laws including but not limited to the export and import regulations of other countries.',
        'In case a person using the world wide web/internet receives a spam or virus which includes a link to Uden.tech or to any other site maintained, operated or owned by DSPL, it should not be held responsible for the same. DSPL assumes no responsibility for such mails.',
        'The services provided by the websites maintained, operated or owned by DSPL do not extend to acting as an agent (express or implied) on behalf of any subscriber or user.',
        'DSPL has no agents and does not operate through any agents save for those specifically mentioned on the home page of the website.',
        'The Terms and conditions mentioned above regulate the usage of Uden.tech. Any person using Uden.tech in violation of the stipulations contained in the Terms and Conditions of Uden.tech shall render himself/herself liable to appropriate action in a court of law both civil and criminal.',
        'BY ACCEPTING THESE TERMS AND CONDITIONS, YOU AGREE TO INDEMNIFY AND OTHERWISE HOLD HARMLESS DSPL, ITS DIRECTORS, OFFICERS, EMPLOYERS, AGENTS, SUBSIDIARIES, AFFILIATES AND OTHER PARTNERS FROM ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, RELATING TO, OR RESULTING FROM YOUR USE OF THE SERVICES OBTAINED THROUGH UDEN.TECHINCLUDING BUT NOT LIMITED TO INFORMATION PROVIDED BY YOU OR ANY OTHER MATTER RELATING TO UDEN.IN. ANY REFERENCE TO DUTIES AND TAXES ETC IN THESE TERMS OF USE SHALL INCLUDE GOODS AND SERVICES TAX (HEREIN REFERRED AS GST) FROM THE DATE GST LAW IS IMPLEMENTED IN INDIA. ANY ADDITIONAL TAX LIABILITY ARISING ON ACCOUNT OF INTRODUCTION OF GST (WHETHER ON ACCOUNT OF INCREASE IN RATE OR ANY CHANGE BROUGHT IN BY THE NEW TAX REGIME) WOULD BE RECOVERED OVER AND ABOVE THE AGREED CONTRACT PRICE / SERVICE FEE.',
        'If any dispute arises between a user/users and DSPL arising out of use of Uden.tech or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these Terms and Conditions, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by the Company. Decision of the arbitrator shall be final and binding on both the parties to the dispute. The place of arbitration shall be New Delhi, India. The Arbitration & Conciliation Act, 1996 as amended, shall govern the arbitration proceedings.',
        'These Terms and Conditions shall be governed by the laws of Republic of India. The exclusive forum for any disputes arising out of or relating to these Terms of Use shall be a court of law located in New Delhi, India.',
        'Digverve, Digverve India, DSPL and Digverve Solutions Pvt. Ltd. are used interchangeably and are synonymous.',
        {
          link:<Typography>The user of Uden.tech is subject to the  <Link href={AppRoutes.PRIVACY}>Privacy Policy</Link> available through this link.</Typography>
        }



      ]
    }
  ]

    
}

export default TermsAndConditionsConst